name: menu_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.1
  get_it: ^7.2.0
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  money_formatter: ^0.0.4
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  dio: ^5.0.3
  shimmer_animation: ^2.1.0+1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
    
  uses-material-design: true
